### PR TITLE
Minify suggestions data files and add GitHub action on release

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
This PR adds json files minification to the csv to json conversion script. It also introduces GitHub action which adds compressed data folder to latest released versions of suggestions.

### How to review 
Run the script and check if it produces correct json files, check if GitHub action works (similar one used in schemas repo).

****[Here's a fork with a json artifact attached](https://github.com/petechd/eq-lookup-suggestions-data). Go to that address if you want to check if release GitHub action is working.****

### CODE REVIEW

**Comment by petechd** [comment]
[Minify suggestions data files on release (S)](https://trello.com/c/I2euQWuK/4363-minify-suggestions-data-files-on-release-s)

**Review by MebinAbraham — COMMENTED** [review]
Not totally against it but it is common to keep the source unminified and then minify it at build time. i.e that is the pattern used by DS etc.

**Comment by petechd** [comment]
> Not totally against it but it is common to keep the source unminified and then minify it at build time. i.e that is the pattern used by DS etc.

There is another source here: csv files, so we don't need unminified json?

**Comment by MebinAbraham** [comment]
> > Not totally against it but it is common to keep the source unminified and then minify it at build time. i.e that is the pattern used by DS etc.
> 
> There is another source here: csv files, so we don't need unminified json?

That's a good point and also means do we even want to have the JSON in source?. The JSON can be generated at build time, similar to how we don't commit built schemas and how they are generated at build time.

**Comment by petechd** [comment]
**[Here's a fork with a json artifact attached](https://github.com/petechd/eq-lookup-suggestions-data). Go to that address if you want to check if release GitHub action is working.**

**Review by MebinAbraham — APPROVED** [review]
Approving on the basis that the fork seems to work as expected. 👍 

Note, the README should be updated with the new approach as some info is redundant now. I will let the 2nd reviewer look at that as I am away until Monday now.

**Review by berroar — COMMENTED** [review]
As @MebinAbraham commented I think the readme needs to be updated as the bit under `Front-end json files` is all done in the Github action. It should mention that the json files are generated automatically, as there isn't really any real reason to run this script manually anymore?

**Comment by berroar** [comment]
Also under `This repository contains versioned TextField suggestion data for eq-questionnaire-runner` in the Readme there is a list of the .json files, but they are no longer held in this repository

**Review by JamesGardiner — APPROVED** [review]

**Pull request merged**
